//tealium universal tag - utag.170 ut4.0.202301091048, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"dom.domain":"domain","ab_test_population":"ab_test_population","eVar23":"evar23","internal_campaign":"internal_campaign","external_attribution_campaign":"external_attribution_campaign","external_attribution_entity":"external_attribution_entity","external_attribution_thematic":"external_attribution_thematic","external_attribution_type":"external_attribution_type","subscriber_status":"subscriber_status","login_status":"login_status","pageName":"pagename","page_level_1":"page_level_1","page_level_2":"page_level_2","page_level_3":"page_level_3","page_level_4":"page_level_4","page_level_5":"page_level_5","prop19":"prop19","browser_name":"browser_name","platform_name":"platform_name","app_zone":"app_zone","country":"country","pref_ads":"pref_ads","pref_analytics":"pref_analytics","pref_reco":"pref_reco","product_category":"product_category","product_code":"product_code","product_price":"product_price","content_id":"content_id","content_in_offer":"content_in_offer","channel":"channel","genre":"genre","subgenre":"subgenre","prop11":"type","prop24":"rubrique","mics_event_type":"mics_event_type","mics_sitetoken":"mics_sitetoken","device_key":"device_key","dom.url":"url","purchaseID":"purchaseID","cp.segment":"segment_AB","id_analytics":"user_id"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
!function(a,b,c){"use strict";function d(a){var b=e[c]||{};e[c]=b,b[a]||(b[a]=function(){e._queue[c].push({method:a,args:Array.prototype.slice.apply(arguments)})})}var e=a.scimhtiraidem||{},f="init call config push pushDefault addProperties addProperty onFinish onStart _reset".split(" ");e._queue=e._queue||{},e._names=e._names||[],e._names.push(c),e._queue[c]=e._queue[c]||[],e._startTime=(new Date).getTime(),e._snippetVersion="2.0";for(var g=0;g<f.length;g++)d(f[g]);a.scimhtiraidem=e,a[c]=e[c];var h=b.createElement("script");h.setAttribute("type","text/javascript"),h.setAttribute("src","https://static.mediarithmics.com/tag/1/tag.min.js"),h.setAttribute("async","true"),b.getElementsByTagName("script")[0].parentNode.appendChild(h)}(window,document,"mics_canal");var siteToken=u.data.mics_sitetoken;mics_canal.init(siteToken);mics_canal.call('syncFeeds');function safeAdd(v,t){if(!v)return undefined;if(t==="int")return parseInt(v)?parseInt(v):undefined;if(t==="array")return Array.isArray(v)?v:undefined;if(t==="boolean")return typeof v==="boolean"?v:undefined;if(t==="float")return parseFloat(v)?parseFloat(v):undefined;return v;}
var eventData={navigation:{}};if(safeAdd(u.data.ab_test_population,"string")){eventData.navigation.ab_test_population=safeAdd(u.data.ab_test_population,"string");}
if(safeAdd(u.data.evar23,"string")){eventData.navigation.funnel_step=safeAdd(u.data.evar23,"string");}
if(safeAdd(u.data.external_attribution_campaign,"string")){eventData.navigation.attribution={internal_campaign:safeAdd(u.data.internal_campaign,"string"),external_attribution_campaign:safeAdd(u.data.external_attribution_campaign,"string"),external_attribution_entity:safeAdd(u.data.external_attribution_entity,"string"),external_attribution_thematic:safeAdd(u.data.external_attribution_thematic,"string"),external_attribution_type:safeAdd(u.data.external_attribution_type,"string")}}
if(safeAdd(u.data.subscriber_status,"string")){eventData.navigation.visitor_status={subscriber_status:safeAdd(u.data.subscriber_status,"string"),login_status:safeAdd(u.data.login_status,"string")};}
if(safeAdd(u.data.pagename,"string")){eventData.navigation.page={page_name:safeAdd(u.data.pagename,"string"),level_1:safeAdd(u.data.page_level_1,"string"),level_2:safeAdd(u.data.page_level_2,"string"),level_3:safeAdd(u.data.page_level_3,"string"),level_4:safeAdd(u.data.page_level_4,"string"),level_5:safeAdd(u.data.page_level_5,"string")};}
if(safeAdd(u.data.channel,"string")){eventData.navigation.site={domain_name:safeAdd(u.data.domain,"string"),site_name:safeAdd(u.data.channel,"string"),browser:safeAdd(u.data.browser_name,"string"),platform:safeAdd(u.data.platform_name,"string"),app_zone:safeAdd(u.data.app_zone,"string"),country:safeAdd(u.data.country,"string")};}
if(safeAdd(utag_data.pref_ads,"string")){eventData.consent={pref_ads:safeAdd(utag_data.pref_ads,"string"),pref_analytics:safeAdd(utag_data.pref_analytics,"string"),pref_reco:safeAdd(utag_data.pref_reco,"string")};}
if(safeAdd(u.data.product_code,"string")){eventData.$items=[];eventData.$items.push({$category:safeAdd(u.data.product_category,"string"),$id:safeAdd(u.data.product_code,"string"),$qty:1,$price:safeAdd(u.data.product_price,"float")});}
if(safeAdd(u.data.content_id,"string")){eventData.content={content_id:safeAdd(u.data.content_id,"string"),in_offer:safeAdd(u.data.content_in_offer,"string"),content_channel:safeAdd(u.data.prop19,"string")};}
if(u.data.device_key!==undefined&&u.data.device_key!==""){mics_canal.addProperty("$device_id",u.data.device_key);}
if(u.data.purchaseID!==undefined&&u.data.purchaseID!==""){mics_canal.addProperty("transaction_id",u.data.purchaseID);}
if(u.data.user_id!==undefined&&u.data.user_id!==""&&u.data.user_id!=="Anonymous"){mics_canal.addProperty("$user_account_id",u.data.user_id);}
utag.DB(document.location.toString());utag.DB(utag.data["dom.url"]);utag.DB(document.referrer);utag.DB(utag.data["dom.referrer"]);mics_canal.addProperty('$url',u.data.url);if(u.data["segment_AB"]!==undefined&&u.data["segment_AB"]!=="")
{eventData.segment_AB=safeAdd(u.data["segment_AB"],"string")}
mics_canal.push(u.data.mics_event_type,eventData);if(!u.initialized){}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("170","canalplus.mycanal-web");}catch(error){utag.DB(error);}
